DjangoStoreApp/urls.py
from django.conf.urls import url, include
# from django.contrib import admin


urlpatterns = [
    url(r'^user/', include('authapp.urls')),
    url(r'', include('homeapp.urls')),    
    # url(r'^admin/', admin.site.urls),    
]

authapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .forms import UserLoginForm
from .views import signup_page

app_name = 'authapp'
urlpatterns = [
    url(r'^login/$', auth_views.login, 
        {
            'template_name': 'authapp/login.html',
            'authentication_form': UserLoginForm
        }, 
        name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', signup_page, name='signup'),
]

homeapp/urls.py
from django.conf.urls import url
from django.shortcuts import redirect

from . import views


app_name = 'homeapp'
urlpatterns = [
    url(r'^goapp/', views.gotogo, name='goapp'),
    url(r'', views.home_view, name='home'),    
]

authapp/forms.py
import re

from django import forms
from django.forms import ModelForm, CharField, TextInput, PasswordInput, ValidationError
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=254, label='', widget=TextInput(attrs = {'placeholder': 'login'}))
    password = forms.CharField(max_length=254, label='', widget=PasswordInput(attrs = {'placeholder': 'password'}))


class UserSignupForm(ModelForm):
    confirm_password = CharField(max_length=16, label='', widget=PasswordInput(attrs = {'placeholder': 'confirm password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'confirm_password']
        labels = {
            'email': '', 
            'username': '', 
            'password': '', 
        }
        widgets = {
            'email' : TextInput(attrs = {'placeholder': 'e-mail'}),
            'username' : TextInput(attrs = {'placeholder': 'login'}),
            'password' : PasswordInput(attrs = {'placeholder': 'password'}),            
        }

    def __init__(self, *args, **kwargs):
        super(UserSignupForm, self).__init__(*args, **kwargs)

        for fieldname in self.Meta.fields:
            self.fields[fieldname].help_text = None

    def clean(self):
        cleaned_data = super(ModelForm, self).clean()

        # sanitization of password
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and password != confirm_password:
            error_message = "password and confirm password fields does not match"
            self.add_error('password', error_message)

        # sanitization of username
        login = cleaned_data.get("username")

        if not re.search(r'^[a-zA-Z]\w{3,14}$', login):
            error_message = "Login must contain only alfanumeric characters and the underscore"
            self.add_error('username', error_message)
            return
        else:
            try:
                User.objects.get(username=login)
            except ObjectDoesNotExist:
                return
            else:
                error_message = "The same user login does already exist"
                self.add_error('username', error_message)

authapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .forms import UserSignupForm


def signup_page(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(
                username = form.cleaned_data['username'],
                email = form.cleaned_data['email'],
                password = form.cleaned_data['password']
            )
            return HttpResponseRedirect(reverse('authapp:login'))
        # form is not valid
        return render(request, 'authapp/signup.html', {'form': form})
    #GET
    form = UserSignupForm()
    return render(request, 'authapp/signup.html', {'form': form})

homeapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views.decorators.http import require_GET

@require_GET
def home_view(request):
    return render(request, 'homeapp/home.html', {
        'content': "Hey, folks! Here you are able to register and login, also check my ",
        'goappLinkText': "Go web site",
        })

def gotogo(request):
    return redirect('https://self-praiser-app.herokuapp.com/')

authapp/templates/authapp/login.html
{% extends "base.html" %}

{% block title %}User Login{% endblock %}

{% block content %}
<div class="auth">
    <form id="182" action="{% url 'authapp:login' %}" method="POST">
        {% csrf_token %}
        
        {% if form.subject.errors %}
            {% for error in form.subject.errors %}
                {{ error|escape }}
            {% endfor %}
        {% endif %}

        {{ form.as_p }}
    </form>
</div>
<div class="auth">
    <input class="button" type="submit" value="login" form="182"/>    
</div>
{% endblock %}

authapp/templates/authapp/signup.html
{% extends "base.html" %}

{% block title %}User Signup Page{% endblock %}

{% block content %}
<div class="auth">
    <form id="182" action="{% url 'authapp:signup' %}" method="POST">
        {% csrf_token %}
        
        {% if form.subject.errors %}
            {% for error in form.subject.errors %}
                {{ error|escape }}
            {% endfor %}
        {% endif %}

        {{ form.as_p }}
    </form>
</div>
<div class="auth">
    <input class="button" type="submit" value="sign up" form="182"/>    
</div>
{% endblock %}

homeapp/templates/homeapp/home.html
{% extends "base.html" %}

{% block title %} Home Page {% endblock %}

{% block welcome %}
    {% if user.is_authenticated %}
        <h3>Welcome, {{ user.username }}!</h3>
    {% endif %}
{% endblock %}

{% block content %}
<div>
    <h1>
        {{ content }} 
        <a href="{% url 'homeapp:goapp' %}">{{ goappLinkText }}</a>
    </h1>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesHome.css' %}">
</head>
<body>

    <div class="top-menu">
        <ul>
            <li><a href="{% url 'homeapp:home' %}">home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'authapp:logout' %}">logout</a></li>
            {% else %}
                <li><a href="{% url 'authapp:login' %}">login</a></li>
                <li><a href="{% url 'authapp:signup' %}">signup</a></li>
            {% endif %}
        </ul>
    </div>

    {% block welcome %}{% endblock %}

    {% block content %}{% endblock %}

    <div class="footer">        
        <p>made by Rybnikov Vladimir, 2017</p>
    </div>
    <div class="footer">        
        <p id="footer2">created using django 1.10</p>
    </div>

</body>
</html>